package kz.kazniioir.oncoregistry.domain;
// Generated Apr 13, 2014 1:07:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Localization generated by hbm2java
 */
@Entity
@Table(name="localization"
    ,catalog="oncoregistry"
)
public class Localization  implements java.io.Serializable {


     private int id;
     private String codeIcd;
     private String name;
     private Set<Morbiditysimple2100> morbiditysimple2100s = new HashSet<Morbiditysimple2100>(0);
     private Set<Morbiditysimple> morbiditysimples = new HashSet<Morbiditysimple>(0);
     private Set<Morbidityolap> morbidityolaps = new HashSet<Morbidityolap>(0);

    public Localization() {
    }

	
    public Localization(int id) {
        this.id = id;
    }
    public Localization(int id, String codeIcd, String name, Set<Morbiditysimple2100> morbiditysimple2100s, Set<Morbiditysimple> morbiditysimples, Set<Morbidityolap> morbidityolaps) {
       this.id = id;
       this.codeIcd = codeIcd;
       this.name = name;
       this.morbiditysimple2100s = morbiditysimple2100s;
       this.morbiditysimples = morbiditysimples;
       this.morbidityolaps = morbidityolaps;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="codeICD", length=20)
    public String getCodeIcd() {
        return this.codeIcd;
    }
    
    public void setCodeIcd(String codeIcd) {
        this.codeIcd = codeIcd;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localization")
    public Set<Morbiditysimple2100> getMorbiditysimple2100s() {
        return this.morbiditysimple2100s;
    }
    
    public void setMorbiditysimple2100s(Set<Morbiditysimple2100> morbiditysimple2100s) {
        this.morbiditysimple2100s = morbiditysimple2100s;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localization")
    public Set<Morbiditysimple> getMorbiditysimples() {
        return this.morbiditysimples;
    }
    
    public void setMorbiditysimples(Set<Morbiditysimple> morbiditysimples) {
        this.morbiditysimples = morbiditysimples;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="localization")
    public Set<Morbidityolap> getMorbidityolaps() {
        return this.morbidityolaps;
    }
    
    public void setMorbidityolaps(Set<Morbidityolap> morbidityolaps) {
        this.morbidityolaps = morbidityolaps;
    }




}


