package kz.kazniioir.oncoregistry.domain;
// Generated Apr 13, 2014 1:07:26 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Morbiditysimple2100 generated by hbm2java
 */
@Entity
@Table(name="morbiditysimple2100"
    ,catalog="oncoregistry"
    , uniqueConstraints = @UniqueConstraint(columnNames={"region_id", "year", "localization_id", "younger14Years"}) 
)
public class Morbiditysimple2100  implements java.io.Serializable {


     private Integer id;
     private Localization localization;
     private Region region;
     private Integer year;
     private String filename;
     private Integer younger14years;
     private Integer registeredInTheStartOfYear;
     private Integer vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis;
     private Integer vzyatoNaUchetThisYearFirstTime;
     private Integer from3groupDetectedDuringProfAll;
     private Integer from3groupDetectedDuringProf01and02stage;
     private Integer from3groupDiagnosoConfirmedMorfologically;
     private Integer from3groupHadStage1and2;
     private Integer from3groupHadStage3;
     private Integer from3groupHadStage4;
     private Integer struckOffTheRegisterAll;
     private Integer struckOffTheRegisterGoOut;
     private Integer struckOffTheRegisterDiagNotConfirmed;
     private Integer struckOffTheRegisterNoInfo;
     private Integer struckOffTheRegisterWithDiagBazalioma;
     private Integer struckOffTheRegisterDiedFromAnotherDisease;
     private Integer registeredInTheEndOfYearAll;
     private Integer registeredInTheEndOfYear5yearsAndMore;

    public Morbiditysimple2100() {
    }

    public Morbiditysimple2100(Localization localization, Region region, Integer year, String filename, Integer younger14years, Integer registeredInTheStartOfYear, Integer vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis, Integer vzyatoNaUchetThisYearFirstTime, Integer from3groupDetectedDuringProfAll, Integer from3groupDetectedDuringProf01and02stage, Integer from3groupDiagnosoConfirmedMorfologically, Integer from3groupHadStage1and2, Integer from3groupHadStage3, Integer from3groupHadStage4, Integer struckOffTheRegisterAll, Integer struckOffTheRegisterGoOut, Integer struckOffTheRegisterDiagNotConfirmed, Integer struckOffTheRegisterNoInfo, Integer struckOffTheRegisterWithDiagBazalioma, Integer struckOffTheRegisterDiedFromAnotherDisease, Integer registeredInTheEndOfYearAll, Integer registeredInTheEndOfYear5yearsAndMore) {
       this.localization = localization;
       this.region = region;
       this.year = year;
       this.filename = filename;
       this.younger14years = younger14years;
       this.registeredInTheStartOfYear = registeredInTheStartOfYear;
       this.vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis = vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis;
       this.vzyatoNaUchetThisYearFirstTime = vzyatoNaUchetThisYearFirstTime;
       this.from3groupDetectedDuringProfAll = from3groupDetectedDuringProfAll;
       this.from3groupDetectedDuringProf01and02stage = from3groupDetectedDuringProf01and02stage;
       this.from3groupDiagnosoConfirmedMorfologically = from3groupDiagnosoConfirmedMorfologically;
       this.from3groupHadStage1and2 = from3groupHadStage1and2;
       this.from3groupHadStage3 = from3groupHadStage3;
       this.from3groupHadStage4 = from3groupHadStage4;
       this.struckOffTheRegisterAll = struckOffTheRegisterAll;
       this.struckOffTheRegisterGoOut = struckOffTheRegisterGoOut;
       this.struckOffTheRegisterDiagNotConfirmed = struckOffTheRegisterDiagNotConfirmed;
       this.struckOffTheRegisterNoInfo = struckOffTheRegisterNoInfo;
       this.struckOffTheRegisterWithDiagBazalioma = struckOffTheRegisterWithDiagBazalioma;
       this.struckOffTheRegisterDiedFromAnotherDisease = struckOffTheRegisterDiedFromAnotherDisease;
       this.registeredInTheEndOfYearAll = registeredInTheEndOfYearAll;
       this.registeredInTheEndOfYear5yearsAndMore = registeredInTheEndOfYear5yearsAndMore;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="localization_id")
    public Localization getLocalization() {
        return this.localization;
    }
    
    public void setLocalization(Localization localization) {
        this.localization = localization;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="region_id")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    
    @Column(name="filename", length=100)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="younger14Years")
    public Integer getYounger14years() {
        return this.younger14years;
    }
    
    public void setYounger14years(Integer younger14years) {
        this.younger14years = younger14years;
    }
    
    @Column(name="registeredInTheStartOfYear")
    public Integer getRegisteredInTheStartOfYear() {
        return this.registeredInTheStartOfYear;
    }
    
    public void setRegisteredInTheStartOfYear(Integer registeredInTheStartOfYear) {
        this.registeredInTheStartOfYear = registeredInTheStartOfYear;
    }
    
    @Column(name="vzyatoNaUchetThisYear_WithBeforeDefinedDiagnosis")
    public Integer getVzyatoNaUchetThisYearWithBeforeDefinedDiagnosis() {
        return this.vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis;
    }
    
    public void setVzyatoNaUchetThisYearWithBeforeDefinedDiagnosis(Integer vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis) {
        this.vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis = vzyatoNaUchetThisYearWithBeforeDefinedDiagnosis;
    }
    
    @Column(name="vzyatoNaUchetThisYear_FirstTime")
    public Integer getVzyatoNaUchetThisYearFirstTime() {
        return this.vzyatoNaUchetThisYearFirstTime;
    }
    
    public void setVzyatoNaUchetThisYearFirstTime(Integer vzyatoNaUchetThisYearFirstTime) {
        this.vzyatoNaUchetThisYearFirstTime = vzyatoNaUchetThisYearFirstTime;
    }
    
    @Column(name="from3Group_DetectedDuringProfAll")
    public Integer getFrom3groupDetectedDuringProfAll() {
        return this.from3groupDetectedDuringProfAll;
    }
    
    public void setFrom3groupDetectedDuringProfAll(Integer from3groupDetectedDuringProfAll) {
        this.from3groupDetectedDuringProfAll = from3groupDetectedDuringProfAll;
    }
    
    @Column(name="from3Group_DetectedDuringProf01And02Stage")
    public Integer getFrom3groupDetectedDuringProf01and02stage() {
        return this.from3groupDetectedDuringProf01and02stage;
    }
    
    public void setFrom3groupDetectedDuringProf01and02stage(Integer from3groupDetectedDuringProf01and02stage) {
        this.from3groupDetectedDuringProf01and02stage = from3groupDetectedDuringProf01and02stage;
    }
    
    @Column(name="from3Group_DiagnosoConfirmedMorfologically")
    public Integer getFrom3groupDiagnosoConfirmedMorfologically() {
        return this.from3groupDiagnosoConfirmedMorfologically;
    }
    
    public void setFrom3groupDiagnosoConfirmedMorfologically(Integer from3groupDiagnosoConfirmedMorfologically) {
        this.from3groupDiagnosoConfirmedMorfologically = from3groupDiagnosoConfirmedMorfologically;
    }
    
    @Column(name="from3Group_HadStage1and2")
    public Integer getFrom3groupHadStage1and2() {
        return this.from3groupHadStage1and2;
    }
    
    public void setFrom3groupHadStage1and2(Integer from3groupHadStage1and2) {
        this.from3groupHadStage1and2 = from3groupHadStage1and2;
    }
    
    @Column(name="from3Group_HadStage3")
    public Integer getFrom3groupHadStage3() {
        return this.from3groupHadStage3;
    }
    
    public void setFrom3groupHadStage3(Integer from3groupHadStage3) {
        this.from3groupHadStage3 = from3groupHadStage3;
    }
    
    @Column(name="from3Group_HadStage4")
    public Integer getFrom3groupHadStage4() {
        return this.from3groupHadStage4;
    }
    
    public void setFrom3groupHadStage4(Integer from3groupHadStage4) {
        this.from3groupHadStage4 = from3groupHadStage4;
    }
    
    @Column(name="struckOffTheRegisterAll")
    public Integer getStruckOffTheRegisterAll() {
        return this.struckOffTheRegisterAll;
    }
    
    public void setStruckOffTheRegisterAll(Integer struckOffTheRegisterAll) {
        this.struckOffTheRegisterAll = struckOffTheRegisterAll;
    }
    
    @Column(name="struckOffTheRegisterGoOut")
    public Integer getStruckOffTheRegisterGoOut() {
        return this.struckOffTheRegisterGoOut;
    }
    
    public void setStruckOffTheRegisterGoOut(Integer struckOffTheRegisterGoOut) {
        this.struckOffTheRegisterGoOut = struckOffTheRegisterGoOut;
    }
    
    @Column(name="struckOffTheRegisterDiagNotConfirmed")
    public Integer getStruckOffTheRegisterDiagNotConfirmed() {
        return this.struckOffTheRegisterDiagNotConfirmed;
    }
    
    public void setStruckOffTheRegisterDiagNotConfirmed(Integer struckOffTheRegisterDiagNotConfirmed) {
        this.struckOffTheRegisterDiagNotConfirmed = struckOffTheRegisterDiagNotConfirmed;
    }
    
    @Column(name="struckOffTheRegisterNoInfo")
    public Integer getStruckOffTheRegisterNoInfo() {
        return this.struckOffTheRegisterNoInfo;
    }
    
    public void setStruckOffTheRegisterNoInfo(Integer struckOffTheRegisterNoInfo) {
        this.struckOffTheRegisterNoInfo = struckOffTheRegisterNoInfo;
    }
    
    @Column(name="struckOffTheRegisterWithDiagBazalioma")
    public Integer getStruckOffTheRegisterWithDiagBazalioma() {
        return this.struckOffTheRegisterWithDiagBazalioma;
    }
    
    public void setStruckOffTheRegisterWithDiagBazalioma(Integer struckOffTheRegisterWithDiagBazalioma) {
        this.struckOffTheRegisterWithDiagBazalioma = struckOffTheRegisterWithDiagBazalioma;
    }
    
    @Column(name="struckOffTheRegisterDiedFromAnotherDisease")
    public Integer getStruckOffTheRegisterDiedFromAnotherDisease() {
        return this.struckOffTheRegisterDiedFromAnotherDisease;
    }
    
    public void setStruckOffTheRegisterDiedFromAnotherDisease(Integer struckOffTheRegisterDiedFromAnotherDisease) {
        this.struckOffTheRegisterDiedFromAnotherDisease = struckOffTheRegisterDiedFromAnotherDisease;
    }
    
    @Column(name="registeredInTheEndOfYearAll")
    public Integer getRegisteredInTheEndOfYearAll() {
        return this.registeredInTheEndOfYearAll;
    }
    
    public void setRegisteredInTheEndOfYearAll(Integer registeredInTheEndOfYearAll) {
        this.registeredInTheEndOfYearAll = registeredInTheEndOfYearAll;
    }
    
    @Column(name="registeredInTheEndOfYear5YearsAndMore")
    public Integer getRegisteredInTheEndOfYear5yearsAndMore() {
        return this.registeredInTheEndOfYear5yearsAndMore;
    }
    
    public void setRegisteredInTheEndOfYear5yearsAndMore(Integer registeredInTheEndOfYear5yearsAndMore) {
        this.registeredInTheEndOfYear5yearsAndMore = registeredInTheEndOfYear5yearsAndMore;
    }




}


