package kz.kazniioir.oncoregistry.domain;
// Generated Apr 13, 2014 1:07:26 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Morbidityolap generated by hbm2java
 */
@Entity
@Table(name="morbidityolap"
    ,catalog="oncoregistry"
    , uniqueConstraints = @UniqueConstraint(columnNames={"region_id", "year", "localization_id", "sex_id", "age_id"}) 
)
public class Morbidityolap  implements java.io.Serializable {


     private Integer id;
     private Localization localization;
     private Age age;
     private Region region;
     private Sex sex;
     private Integer year;
     private String filename;
     private Integer morbidity;

    public Morbidityolap() {
    }

    public Morbidityolap(Localization localization, Age age, Region region, Sex sex, Integer year, String filename, Integer morbidity) {
       this.localization = localization;
       this.age = age;
       this.region = region;
       this.sex = sex;
       this.year = year;
       this.filename = filename;
       this.morbidity = morbidity;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="localization_id")
    public Localization getLocalization() {
        return this.localization;
    }
    
    public void setLocalization(Localization localization) {
        this.localization = localization;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="age_id")
    public Age getAge() {
        return this.age;
    }
    
    public void setAge(Age age) {
        this.age = age;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="region_id")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sex_id")
    public Sex getSex() {
        return this.sex;
    }
    
    public void setSex(Sex sex) {
        this.sex = sex;
    }
    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    
    @Column(name="filename", length=100)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="morbidity")
    public Integer getMorbidity() {
        return this.morbidity;
    }
    
    public void setMorbidity(Integer morbidity) {
        this.morbidity = morbidity;
    }




}


