package kz.kazniioir.oncoregistry.domain;
// Generated Apr 13, 2014 1:07:26 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Morbiditysimple generated by hbm2java
 */
@Entity
@Table(name="morbiditysimple"
    ,catalog="oncoregistry"
    , uniqueConstraints = @UniqueConstraint(columnNames={"region_id", "year", "localization_id", "sex_id"}) 
)
public class Morbiditysimple  implements java.io.Serializable {


     private Integer id;
     private Localization localization;
     private Region region;
     private Sex sex;
     private Integer year;
     private String filename;
     private Integer ageall;
     private Integer age04;
     private Integer age59;
     private Integer age1014;
     private Integer age1517;
     private Integer age1819;
     private Integer age2024;
     private Integer age2529;
     private Integer age1529;
     private Integer age3034;
     private Integer age3539;
     private Integer age4044;
     private Integer age4549;
     private Integer age5054;
     private Integer age5559;
     private Integer age6064;
     private Integer age6569;
     private Integer age7074;
     private Integer age7579;
     private Integer age8084;
     private Integer age85;

    public Morbiditysimple() {
    }

    public Morbiditysimple(Localization localization, Region region, Sex sex, Integer year, String filename, Integer ageall, Integer age04, Integer age59, Integer age1014, Integer age1517, Integer age1819, Integer age2024, Integer age2529, Integer age1529, Integer age3034, Integer age3539, Integer age4044, Integer age4549, Integer age5054, Integer age5559, Integer age6064, Integer age6569, Integer age7074, Integer age7579, Integer age8084, Integer age85) {
       this.localization = localization;
       this.region = region;
       this.sex = sex;
       this.year = year;
       this.filename = filename;
       this.ageall = ageall;
       this.age04 = age04;
       this.age59 = age59;
       this.age1014 = age1014;
       this.age1517 = age1517;
       this.age1819 = age1819;
       this.age2024 = age2024;
       this.age2529 = age2529;
       this.age1529 = age1529;
       this.age3034 = age3034;
       this.age3539 = age3539;
       this.age4044 = age4044;
       this.age4549 = age4549;
       this.age5054 = age5054;
       this.age5559 = age5559;
       this.age6064 = age6064;
       this.age6569 = age6569;
       this.age7074 = age7074;
       this.age7579 = age7579;
       this.age8084 = age8084;
       this.age85 = age85;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="localization_id")
    public Localization getLocalization() {
        return this.localization;
    }
    
    public void setLocalization(Localization localization) {
        this.localization = localization;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="region_id")
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sex_id")
    public Sex getSex() {
        return this.sex;
    }
    
    public void setSex(Sex sex) {
        this.sex = sex;
    }
    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    
    @Column(name="filename", length=100)
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }
    
    @Column(name="ageall")
    public Integer getAgeall() {
        return this.ageall;
    }
    
    public void setAgeall(Integer ageall) {
        this.ageall = ageall;
    }
    
    @Column(name="age0_4")
    public Integer getAge04() {
        return this.age04;
    }
    
    public void setAge04(Integer age04) {
        this.age04 = age04;
    }
    
    @Column(name="age5_9")
    public Integer getAge59() {
        return this.age59;
    }
    
    public void setAge59(Integer age59) {
        this.age59 = age59;
    }
    
    @Column(name="age10_14")
    public Integer getAge1014() {
        return this.age1014;
    }
    
    public void setAge1014(Integer age1014) {
        this.age1014 = age1014;
    }
    
    @Column(name="age15_17")
    public Integer getAge1517() {
        return this.age1517;
    }
    
    public void setAge1517(Integer age1517) {
        this.age1517 = age1517;
    }
    
    @Column(name="age18_19")
    public Integer getAge1819() {
        return this.age1819;
    }
    
    public void setAge1819(Integer age1819) {
        this.age1819 = age1819;
    }
    
    @Column(name="age20_24")
    public Integer getAge2024() {
        return this.age2024;
    }
    
    public void setAge2024(Integer age2024) {
        this.age2024 = age2024;
    }
    
    @Column(name="age25_29")
    public Integer getAge2529() {
        return this.age2529;
    }
    
    public void setAge2529(Integer age2529) {
        this.age2529 = age2529;
    }
    
    @Column(name="age15_29")
    public Integer getAge1529() {
        return this.age1529;
    }
    
    public void setAge1529(Integer age1529) {
        this.age1529 = age1529;
    }
    
    @Column(name="age30_34")
    public Integer getAge3034() {
        return this.age3034;
    }
    
    public void setAge3034(Integer age3034) {
        this.age3034 = age3034;
    }
    
    @Column(name="age35_39")
    public Integer getAge3539() {
        return this.age3539;
    }
    
    public void setAge3539(Integer age3539) {
        this.age3539 = age3539;
    }
    
    @Column(name="age40_44")
    public Integer getAge4044() {
        return this.age4044;
    }
    
    public void setAge4044(Integer age4044) {
        this.age4044 = age4044;
    }
    
    @Column(name="age45_49")
    public Integer getAge4549() {
        return this.age4549;
    }
    
    public void setAge4549(Integer age4549) {
        this.age4549 = age4549;
    }
    
    @Column(name="age50_54")
    public Integer getAge5054() {
        return this.age5054;
    }
    
    public void setAge5054(Integer age5054) {
        this.age5054 = age5054;
    }
    
    @Column(name="age55_59")
    public Integer getAge5559() {
        return this.age5559;
    }
    
    public void setAge5559(Integer age5559) {
        this.age5559 = age5559;
    }
    
    @Column(name="age60_64")
    public Integer getAge6064() {
        return this.age6064;
    }
    
    public void setAge6064(Integer age6064) {
        this.age6064 = age6064;
    }
    
    @Column(name="age65_69")
    public Integer getAge6569() {
        return this.age6569;
    }
    
    public void setAge6569(Integer age6569) {
        this.age6569 = age6569;
    }
    
    @Column(name="age70_74")
    public Integer getAge7074() {
        return this.age7074;
    }
    
    public void setAge7074(Integer age7074) {
        this.age7074 = age7074;
    }
    
    @Column(name="age75_79")
    public Integer getAge7579() {
        return this.age7579;
    }
    
    public void setAge7579(Integer age7579) {
        this.age7579 = age7579;
    }
    
    @Column(name="age80_84")
    public Integer getAge8084() {
        return this.age8084;
    }
    
    public void setAge8084(Integer age8084) {
        this.age8084 = age8084;
    }
    
    @Column(name="age85")
    public Integer getAge85() {
        return this.age85;
    }
    
    public void setAge85(Integer age85) {
        this.age85 = age85;
    }




}


