package kz.kazniioir.oncoregistry.domain;
// Generated Apr 13, 2014 1:07:26 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Population generated by hbm2java
 */
@Entity
@Table(name="population"
    ,catalog="oncoregistry"
    , uniqueConstraints = @UniqueConstraint(columnNames={"year", "region_id", "sex_id", "age_id", "region_type_id"}) 
)
public class Population  implements java.io.Serializable {


     private Integer id;
     private Age age;
     private Region region;
     private Sex sex;
     private RegionType regionType;
     private int year;
     private int value;

    public Population() {
    }

    public Population(Age age, Region region, Sex sex, RegionType regionType, int year, int value) {
       this.age = age;
       this.region = region;
       this.sex = sex;
       this.regionType = regionType;
       this.year = year;
       this.value = value;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="age_id", nullable=false)
    public Age getAge() {
        return this.age;
    }
    
    public void setAge(Age age) {
        this.age = age;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="region_id", nullable=false)
    public Region getRegion() {
        return this.region;
    }
    
    public void setRegion(Region region) {
        this.region = region;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sex_id", nullable=false)
    public Sex getSex() {
        return this.sex;
    }
    
    public void setSex(Sex sex) {
        this.sex = sex;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="region_type_id", nullable=false)
    public RegionType getRegionType() {
        return this.regionType;
    }
    
    public void setRegionType(RegionType regionType) {
        this.regionType = regionType;
    }
    
    @Column(name="year", nullable=false)
    public int getYear() {
        return this.year;
    }
    
    public void setYear(int year) {
        this.year = year;
    }
    
    @Column(name="value", nullable=false)
    public int getValue() {
        return this.value;
    }
    
    public void setValue(int value) {
        this.value = value;
    }




}


