package kz.kazniioir.oncoregistry.domain;
// Generated Apr 13, 2014 1:07:26 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name="region"
    ,catalog="oncoregistry"
)
public class Region  implements java.io.Serializable {


     private int id;
     private String name;
     private Set<Morbiditysimple2100> morbiditysimple2100s = new HashSet<Morbiditysimple2100>(0);
     private Set<Population> populations = new HashSet<Population>(0);
     private Set<Morbidityolap> morbidityolaps = new HashSet<Morbidityolap>(0);
     private Set<Morbiditysimple> morbiditysimples = new HashSet<Morbiditysimple>(0);

    public Region() {
    }

	
    public Region(int id) {
        this.id = id;
    }
    public Region(int id, String name, Set<Morbiditysimple2100> morbiditysimple2100s, Set<Population> populations, Set<Morbidityolap> morbidityolaps, Set<Morbiditysimple> morbiditysimples) {
       this.id = id;
       this.name = name;
       this.morbiditysimple2100s = morbiditysimple2100s;
       this.populations = populations;
       this.morbidityolaps = morbidityolaps;
       this.morbiditysimples = morbiditysimples;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="region")
    public Set<Morbiditysimple2100> getMorbiditysimple2100s() {
        return this.morbiditysimple2100s;
    }
    
    public void setMorbiditysimple2100s(Set<Morbiditysimple2100> morbiditysimple2100s) {
        this.morbiditysimple2100s = morbiditysimple2100s;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="region")
    public Set<Population> getPopulations() {
        return this.populations;
    }
    
    public void setPopulations(Set<Population> populations) {
        this.populations = populations;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="region")
    public Set<Morbidityolap> getMorbidityolaps() {
        return this.morbidityolaps;
    }
    
    public void setMorbidityolaps(Set<Morbidityolap> morbidityolaps) {
        this.morbidityolaps = morbidityolaps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="region")
    public Set<Morbiditysimple> getMorbiditysimples() {
        return this.morbiditysimples;
    }
    
    public void setMorbiditysimples(Set<Morbiditysimple> morbiditysimples) {
        this.morbiditysimples = morbiditysimples;
    }




}


