package kz.kazniioir.oncoregistry.report.morbidity;

public class StringQueries {

    public static String queryMorbT1 = "select r.name as row_name, m.year as col_name, m.morbidity as morbidity_abs ,ps.value as population from morbidityolap m\n"
            + "            left join population ps ON m.region_id=ps.region_id and m.year=ps.year and m.age_id=ps.age_id and  m.sex_id=ps.sex_id\n"
            + "            inner join region r ON m.region_id=r.id\n"
            + "            where 1=1\n"
            + "            and m.localization_id=1\n"
            + "            and m.sex_id=3\n"
            + "            and m.age_id=10 \n"
            + "            group by m.region_id, m.year\n"
            + "            order by m.region_id, m.year;";
    public static String queryMorbT2 = "  select age.name as row_name, m.year as col_name, m.morbidity as morbidity_abs, ps.value as population\n"
            + " from morbidityolap m \n"
            + " left join  population ps ON m.region_id=ps.region_id and m.year=ps.year and m.age_id=ps.age_id and  m.sex_id=ps.sex_id\n"
            + " inner join age age ON m.age_id=age.id\n"
            + " where 1=1\n"
            + " and m.region_id=17\n"
            + " and m.sex_id=3\n"
            + " and m.localization_id=1\n"
            + " and (age.name = 'все возрасты'\n"
            + " or age.name = '0-4'\n"
            + " or age.name = '5-9'\n"
            + " or  age.name ='10-14'\n"
            + " or  age.name ='15-19'\n"
            + " or  age.name ='20-24'\n"
            + " or  age.name ='25-29'\n"
            + " or  age.name ='30-34'\n"
            + " or  age.name ='35-39'\n"
            + " or age.name  ='40-44'\n"
            + " or age.name  ='45-49'\n"
            + " or age.name  ='50-54'\n"
            + " or age.name  ='55-59'\n"
            + " or age.name  ='60-64'\n"
            + " or age.name  ='65-69'\n"
            + " or  age.name ='70 +')\n"
            + " group by m.age_id, m.year\n"
            + " order by m.age_id, m.year";
    public static String queryMorbT3 = "select s.name as row_name, m.year as col_name, m.morbidity as morbidity_abs , ps.value as population from morbidityolap m\n"
            + "            left join population ps ON m.region_id=ps.region_id and m.year=ps.year and m.age_id=ps.age_id and  m.sex_id=ps.sex_id\n"
            + "            inner join sex s ON m.sex_id=s.id\n"
            + "            where 1=1\n"
            + "            and m.localization_id=1\n"
            + "            and m.age_id=10 \n"
            + "            and m.region_id=17\n"
            + "            group by m.sex_id, m.year\n"
            + "            order by m.sex_id, m.year";
    public static String queryMorbT4 = "select s.name as row_name, m.year as col_name, m.value as morbidity_abs, ps.value as population\n"
            + "from morbidityolap2100 m\n"
            + "left join population ps on m.region_id=ps.region_id and m.year=ps.year\n"
            + "inner join stage s on m.stage_id=s.id\n"
            + "where 1=1 \n"
            + "and m.region_id=17 \n"
            + "and m.localization_id=1\n"
            + "and ps.sex_id=3\n"
            + "group by m.stage_id, m.year\n"
            + "order by  m.stage_id,  m.year";
    public static String queryMorbT5 = "select l.name as row_name, m.year as col_name, m.morbidity as morbidity_abs ,ps.value as population \n"
            + "from morbidityolap m\n"
            + "left join population ps ON m.region_id=ps.region_id and m.year=ps.year and m.age_id=ps.age_id and  m.sex_id=ps.sex_id\n"
            + "inner join `localization` l ON m.`localization_id`=l.id\n"
            + "where 1=1\n"
            + "and m.`region_id`=1\n"
            + "and m.sex_id=3\n"
            + "and m.age_id=10 \n"
            + "group by m.localization_id, m.year\n"
            + "order by m.localization_id, m.year";
}
